### ISSUE TITLE
test failing on Ubuntu 14.10

### ISSUE THREAD

**Issue by amitmurthy** [JuliaParallel/MPI.jl#25]
```
amitm@amitm-macbookpro:~/.julia/v0.4/MPI/test$ mpirun -np 4 julia test_bcast.jl

WARNING: deprecated syntax "{a=>b, ...}" at /home/amitm/.julia/v0.4/MPI/src/mpi-base.jl:19.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /home/amitm/.julia/v0.4/MPI/src/mpi-base.jl:19.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /home/amitm/.julia/v0.4/MPI/src/mpi-base.jl:19.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /home/amitm/.julia/v0.4/MPI/src/mpi-base.jl:19.
Use "Dict{Any,Any}(a=>b, ...)" instead.
Inconsistency detected by ld.so: dl-minimal.c: 136: realloc: Assertion `ptr == alloc_last_block' failed!
Inconsistency detected by ld.so: dl-minimal.c: 136: realloc: Assertion `ptr == alloc_last_block' failed!
Inconsistency detected by ld.so: dl-minimal.c: 136: realloc: Assertion `ptr == alloc_last_block' failed!
Inconsistency detected by ld.so: dl-minimal.c: 136: realloc: Assertion `ptr == alloc_last_block' failed!
--------------------------------------------------------------------------
mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
amitm@amitm-macbookpro:~/.julia/v0.4/MPI/test$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2558 (2015-01-08 07:21 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 2bb647a (0 days old master)
|__/                   |  x86_64-linux-gnu
```

**Comment by lcw** [comment]
I get the same warnings with development version of julia but cannot reproduce the error message.  It looks like there is a bad `realloc` call somewhere.  There is no `realloc` call in MPI.jl so this error might be coming from julia or the MPI library.  Can you try a different version of julia?

**Comment by amitmurthy** [comment]
Yes, it seems to work fine on a different computer with an i5 processor. I suspect it is due to some different compiler options between the julia build and mpi.jl build. I'll try with Julia 0.3.x and see if it works.

**Comment by amitmurthy** [comment]
A google search for that error all showed up issues related to either a) cross-compiling or b) memory allocated by one library being freed/realloc'ed by another. I think we can rule the former out, how about the latter?

**Comment by amitmurthy** [comment]
Also see https://code.google.com/p/chromium/issues/detail?id=31809#c31

**Comment by lcw** [comment]
Hmm.  Can you run `ldd` on the shared library `libjuliampi.so` to see what libraries it is loading?  Maybe it is picking up something it should not.

**Comment by lcw** [comment]
It would also be nice if you could get a stacktrace.

**Comment by amitmurthy** [comment]
`ldd` output. The machine is a macbookpro running Ubuntu 14.10

```
amitm@amitm-macbookpro:~/.julia/v0.4/MPI/deps/usr/lib$ ldd libjuliampi.so 
        linux-vdso.so.1 =>  (0x00007fff8bbfc000)
        libmpi_f77.so.1 => /usr/lib/libmpi_f77.so.1 (0x00007fbe4fdee000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbe50243000)
        libmpi.so.1 => /usr/lib/libmpi.so.1 (0x00007fbe4fa6d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbe4f84e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbe4f489000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fbe4f286000)
        libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007fbe4f045000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007fbe4ee3b000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007fbe4ec30000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbe4ea2b000)
```

gdb backtrace

```
Breakpoint 1, realloc (ptr=0x2fd5ff0, n=272) at dl-minimal.c:136
136     dl-minimal.c: No such file or directory.
(gdb) bt
#0  realloc (ptr=0x2fd5ff0, n=272) at dl-minimal.c:136
#1  0x00007fffdcb735a5 in opal_value_array_set_size () from /usr/lib/libmpi.so.1
#2  0x00007fffdcb61e81 in ?? () from /usr/lib/libmpi.so.1
#3  0x00007fffdcb61407 in mca_base_param_reg_string_name () from /usr/lib/libmpi.so.1
#4  0x00007fffdcb61536 in mca_base_param_recache_files () from /usr/lib/libmpi.so.1
#5  0x00007fffdcb61ae7 in mca_base_param_init () from /usr/lib/libmpi.so.1
#6  0x00007fffdcb61e4d in ?? () from /usr/lib/libmpi.so.1
#7  0x00007fffdcb61407 in mca_base_param_reg_string_name () from /usr/lib/libmpi.so.1
#8  0x00007fffdcb659ed in opal_net_init () from /usr/lib/libmpi.so.1
#9  0x00007fffdcb715a5 in opal_init_util () from /usr/lib/libmpi.so.1
#10 0x00007fffdcac0f0b in ompi_mpi_init () from /usr/lib/libmpi.so.1
#11 0x00007fffdcad8660 in PMPI_Init () from /usr/lib/libmpi.so.1
#12 0x00007fffdce0f0f8 in pmpi_init__ () from /usr/lib/libmpi_f77.so.1
#13 0x00007ffff7e73a2f in ?? ()
#14 0x0000000000000000 in ?? ()
(gdb) c
```

**Comment by amitmurthy** [comment]
I removed the ubuntu packaged openmpi packages. Downloaded, built and installed openmpi from source.

Reinstalled MPI.jl after deleting the existing MPI directory.

I now get

```
amitm@amitm-macbookpro:~/.julia/v0.4/MPI/examples$ mpirun -np 1 julia 01-hello.jl 

WARNING: deprecated syntax "{a=>b, ...}" at /home/amitm/.julia/v0.4/MPI/src/mpi-base.jl:19.
Use "Dict{Any,Any}(a=>b, ...)" instead.
*** Error in `julia': malloc(): memory corruption: 0x0000000002ab2d70 ***
```

**Comment by amitmurthy** [comment]
Some good news - I am able to get `MPI.jl` working with `mpich`.  Uninstalled `openmpi` and installed `mpich` via `apt-get` and the tests under `MPI.jl` all work.

**Comment by amitmurthy** [comment]
`mpich` does not seem to have an option to create separate files locally to capture the stdout of each worker. Does anyone know if this is possible in `mpich`? It is critical for the `MPIManager` as currently coded to work.

**Comment by eschnett** [comment]
To capture stdout into a file, you can redirect stdout from within Julia.

**Comment by eschnett** [comment]
I believe Ubuntu can provide different MPI versions. Can you try installing e.g. OpenMPI instead of MPICH?

**Comment by amitmurthy** [comment]
@eschnett , that will work only for local MPI workers and not for remote ones.

With openmpi I have the memory error as described above on my laptop (Haswell i7). There is no issue on my work desktop which is an i5.

With mpich, I don't know how to capture the stdout for remote workers in the master process.

**Comment by eschnett** [comment]
@amitmurthy Oh, you want to capture the worker's stdout on the master, not into an arbitrary file. I don't know of a method either. My design would have been to have the worker use `MPI_Send` to send the respective data, and to use `MPI_Recv` (maybe combined with `MPI_Iprobe`) on the master to receive these data. Note that `MPI.jl` has very convenient wrappers for this, so that using `send` and `recv` or `irecv` should be quite convenient.

**Comment by amitmurthy** [comment]
The model we are currently following is that Julia master (julia pid 1) process is not part of the MPI Comm world. Thus the Julia master process executes `mpirun` which in turn will launch the MPI processes. We then proceed to call `MPI_Init` only on the newly launched Julia workers - this makes them part of the MPI world.

I need the stdout of all the workers because

a) the newly launched workers also listen on a free port and print this host:port information to STDOUT. This is how the master connects them as part of the julia socket cluster (same set of processes but different from the MPI connections). It reads the first line of the stdout of each worker and connects to them.

b) Current julia parallel users are used to seeing any writes to stdout on the master terminal. We can thus continue to support this functionality.

The reason we have opted for this model is that the julia master is free from computational work and acts purely as a driver of the distributed work. It is free for interactively checking the progress of computation, plotting intermediate results, etc.

It also allows for a model were a REPL on a user's laptop is the driver, while beefier machines on the network or a public cloud can do the actual computation. The user's laptop will still need MPI.jl installed, but the master process on the laptop will not be part of MPI comm world.

Since the julia master is not part of MPI world, we cannot use MPI calls to send back events to the master.

`openmpi` has mechanism where it captures the stdout (even of remote workers) and writes to a local file. On the master I just execute a `tail -f` on the file and thus capture the stout.

`mpich` does not seem to provide such a mechanism.

**Comment by amitmurthy** [comment]
On the system on which it works `ldd` prints

```
amitm@amitm-laptop:~/.julia/v0.4/MPI/deps/usr/lib$ ldd libjuliampi.so 
        linux-vdso.so.1 =>  (0x00007fff969b8000)
        libmpi_f77.so.1 => /usr/lib/libmpi_f77.so.1 (0x00007feff109b000)
        libmpi.so.1 => /usr/lib/libmpi.so.1 (0x00007feff0d1a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007feff0afb000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007feff0735000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007feff0532000)
        libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007feff02f1000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007feff00e7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007feff14f5000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007fefefedc000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fefefcd7000)
```

On the failing system:
```
amitm@amitm-macbookpro:~/.julia/v0.4/MPI/deps/usr/lib$ ldd libjuliampi.so 
        linux-vdso.so.1 =>  (0x00007fff8bbfc000)
        libmpi_f77.so.1 => /usr/lib/libmpi_f77.so.1 (0x00007fbe4fdee000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fbe50243000)
        libmpi.so.1 => /usr/lib/libmpi.so.1 (0x00007fbe4fa6d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbe4f84e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbe4f489000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fbe4f286000)
        libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007fbe4f045000)
        libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007fbe4ee3b000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007fbe4ec30000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbe4ea2b000)
```

The only difference is that on the failing system `/lib64/ld-linux-x86-64.so.2`  occurs higher up in the order. Where is the order being set and can it be changed?

**Comment by amitmurthy** [comment]
The `realloc` from `ld.so` being loaded does seem to the issue - also see https://www.technovelty.org/linux/toolchains-libc-and-interesting-interactions.html

**Comment by amitmurthy** [comment]
@lcw, a basic question - what is the role of `libjuliampi.so` ? Why don't we `ccall` directly into the `openmpi/mpich` fortran libraries?

**Comment by eschnett** [comment]
@amitmurthy As far as I understand: The MPI libraries may not be available as shared libraries, but only as static libraries. They also have different names on each system. Using `libjuliampi.so` pushes all this logic into the install script. It is also in general not possible to simply switch to a different MPI library, since there are constants (defined in header files) that must match. Using `cmake` simplifies this logic tremendously.

**Comment by eschnett** [comment]
@amitmurthy Did you try reinstalling MPI (from scratch) on the failing system? If you built the package yourself, you would also need to clear the package cache. If `ld.so` is the problem, then it may be `libmpi_f77` that has the wrong dependencies.

**Comment by lcw** [comment]
@amitmurthy: The understanding that @eschnett is mine as well.  I was trying to put all of the logic figuring out the MPI libraries into the build process.  I am leaning CMake to figure this out but that looks to be a problem.  For example I only specify the link libraries as
```
target_link_libraries(juliampi ${MPI_Fortran_LIBRARIES})
```
where `MPI_Fortran_LIBRARIES` is figured out by CMake.  So I am with @eschnett, I guess there is some wrong dependencies in your MPI implementation.  Not sure if this help.

You could try a minimum example only using CMake and Fortran and see if you can reproduce the error.  If so we can send it to the CMake list to see if they can help figuring out the problem.

**Comment by amitmurthy** [comment]
Seems to be a problem that shows up on Ubuntu 14.10

I have a system on AWS that I can email ssh credentials for if anyone wants to take a look. Do let me know and I'll send the ip-address / ssh keyfile.

**Comment by lcw** [comment]
Cool.  `libjuliampi.so` is just a shared library that links to the MPI Fortran installation.  It has a dummy function in there so that it is built.  You can try to create this library by hand to see if it is an issue with CMake creating the library or a problem with how the Ubuntu distributes the libraries.

**Comment by ViralBShah** [comment]
It failed even when compiling with mpif77 by hand. It seems something is strangely broken on Ubuntu 14.10.

**Comment by lcw** [comment]
Weird.  I will close this issue for now.  Feel free to reopen it if we need to change something in MPI.jl.

**Comment by amitmurthy** [comment]
Reopening this since

a) `MPI.jl` is practically unusable on Ubuntu 14.10.
b) By keeping it open, hopefully someone can provide a workaround. Just to add to Viral's comment -`mpif77` used to compile a fortran program works fine, it is only a fortran shared library that is the issue.

**Comment by eschnett** [comment]
Was this problem with OpenMPI? An OpenMPI problem was recently solved; see #70.

**Comment by eschnett** [comment]
I assume this was resolved.

**Comment by mlubin** [comment]
Not resolved. I'm on Ubuntu 15.10 using the system openmpi packages and getting the same error message as @amitmurthy originally:
```
Inconsistency detected by ld.so: dl-minimal.c: 136: realloc: Assertion `ptr == alloc_last_block' failed!
```

**Comment by eschnett** [comment]
@mlubin Please confirm your system details: You are using Ubuntu 15.10, have installed the standard OpenMPI packages there, and are using Julia 0.4?

**Comment by mlubin** [comment]
> Please confirm your system details: You are using Ubuntu 15.10, have installed the standard OpenMPI packages there, and are using Julia 0.4?

Correct

**Comment by eschnett** [comment]
I can reproduce the problem on Ubuntu 15.10. Things are working fine on Ubuntu 14.04.
